# Generated by Django 5.0.14 on 2026-06-01 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionCadena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cadena', models.CharField(blank=True, max_length=30)),
                ('elongacion_actual_pct', models.FloatField(blank=True, help_text='Elongación actual de la cadena (%)', null=True)),
                ('longitud_nominal_mm', models.FloatField(blank=True, help_text='Longitud nominal de referencia (mm)', null=True)),
                ('longitud_actual_mm', models.FloatField(blank=True, help_text='Longitud medida en la última inspección (mm)', null=True)),
                ('tasa_elongacion_pct_1000h', models.FloatField(default=0.0, help_text='Incremento de elongación (%) por cada 1000 horas')),
                ('horas_restantes', models.FloatField(default=99999, help_text='Horas estimadas hasta alcanzar el límite de elongación')),
                ('fecha_reemplazo_estimada', models.DateField(blank=True, help_text='Fecha estimada de reemplazo de cadena', null=True)),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('ATENCION', 'Atención'), ('CRITICO', 'Crítico')], default='OK', max_length=20)),
                ('ultima_medicion_fecha', models.DateField(blank=True, null=True)),
                ('ultima_medicion_horometro', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proyeccion_cadena', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Proyección de Cadena',
                'verbose_name_plural': 'Proyecciones de Cadenas',
                'ordering': ['estado', 'elongacion_actual_pct'],
            },
        ),
        migrations.CreateModel(
            name='MedicionCadena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la medición')),
                ('horometro', models.FloatField(blank=True, help_text='Horómetro del equipo al momento de medir', null=True)),
                ('tipo_cadena', models.CharField(choices=[('spreader_principal', 'Cadena Principal de Spreader'), ('spreader_secundaria', 'Cadena Secundaria de Spreader'), ('elevacion', 'Cadena de Elevación'), ('traslacion', 'Cadena de Traslación'), ('otro', 'Otro (ver observaciones)')], default='spreader_principal', help_text='Tipo/ubicación de la cadena medida', max_length=30)),
                ('longitud_nominal_mm', models.FloatField(help_text='Longitud nominal (nueva) del tramo medido en mm')),
                ('longitud_medida_mm', models.FloatField(help_text='Longitud medida actual del mismo tramo en mm')),
                ('num_eslabones', models.IntegerField(default=12, help_text='Número de eslabones en el tramo medido (recomendado: 10-12)')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_cadena', to='equipos.equipo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones_cadena', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medición de Cadena',
                'verbose_name_plural': 'Mediciones de Cadenas',
                'ordering': ['-fecha', 'equipo'],
                'indexes': [models.Index(fields=['equipo', 'fecha'], name='cadenas_med_equipo__ac18d5_idx')],
            },
        ),
    ]
