# Generated by Django 5.0.14 on 2026-06-01 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadenas', '0001_initial'),
        ('equipos', '0002_equipo_numero_unique_por_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyeccioncadena',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones_cadena', to='equipos.equipo'),
        ),
        migrations.AlterUniqueTogether(
            name='proyeccioncadena',
            unique_together={('equipo', 'tipo_cadena')},
        ),
    ]
