# Generated by Django 5.0.14 on 2026-03-09 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionTurbo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_radial_1000h', models.FloatField(default=0.0, help_text='Crecimiento milimétrico proyectado cada 1000 hrs')),
                ('tasa_axial_1000h', models.FloatField(default=0.0, help_text='Crecimiento milimétrico proyectado cada 1000 hrs')),
                ('horas_motor_restantes', models.FloatField(default=10000, help_text='Horas estimadas de motor restantes hasta límite de tolerancia')),
                ('estado', models.CharField(choices=[('OK', 'Ok'), ('ATENCION', 'Atención'), ('CRITICO', 'Crítico')], default='OK', max_length=20)),
                ('ultima_medicion_fecha', models.DateField(blank=True, null=True)),
                ('ultima_medicion_horometro', models.PositiveIntegerField(blank=True, null=True)),
                ('juego_radial_actual', models.FloatField(blank=True, null=True)),
                ('juego_axial_actual', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proyeccion_turbo', to='equipos.equipo')),
            ],
            options={
                'ordering': ['estado', 'horas_motor_restantes'],
            },
        ),
        migrations.CreateModel(
            name='MedicionTurbo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horometro_motor', models.PositiveIntegerField(help_text='Horas de funcionamiento del motor al momento de la medición')),
                ('juego_radial', models.FloatField(help_text='Juego radial en milímetros (mm)')),
                ('juego_axial', models.FloatField(help_text='Juego axial en milímetros (mm)')),
                ('estado_visual', models.CharField(choices=[('OK', 'Buen estado - Sin anomalías'), ('FUGA_ACEITE', 'Fuga visible de aceite en caracola'), ('ROCE_ASPAS', 'Roce metálico de álabes en carcasa'), ('OTRO', 'Otro (Ver observaciones)')], default='OK', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_turbo', to='equipos.equipo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-horometro_motor'],
                'unique_together': {('equipo', 'fecha', 'horometro_motor')},
            },
        ),
    ]
