# Generated by Django 5.0.14 on 2026-03-05 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaDesgaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('traccion', 'Traccional'), ('direccion', 'Direccional')], max_length=20)),
                ('posicion', models.CharField(max_length=5)),
                ('tasa_mm_dia', models.FloatField(help_text='mm/día (valor absoluto)')),
                ('tasa_mm_hora', models.FloatField(help_text='mm/hora')),
                ('tasa_mm_100h', models.FloatField(help_text='mm/100 horas')),
                ('total_mm_acum', models.FloatField(help_text='mm acumulados usados para cálculo')),
                ('total_dias_acum', models.FloatField(help_text='Días acumulados usados para cálculo')),
                ('n_mediciones', models.IntegerField(default=0)),
                ('calculado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tasa de Desgaste',
                'verbose_name_plural': 'Tasas de Desgaste',
                'ordering': ['tipo', 'marca_nombre', 'posicion'],
                'unique_together': {('marca_nombre', 'tipo', 'posicion')},
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la medición')),
                ('tipo', models.CharField(choices=[('traccion', 'Traccional'), ('direccion', 'Direccional')], max_length=20)),
                ('marca_nombre', models.CharField(help_text='Nombre de marca al momento de medir', max_length=50)),
                ('h1', models.FloatField(blank=True, null=True, verbose_name='H1 (mm)')),
                ('h2', models.FloatField(blank=True, null=True, verbose_name='H2 (mm)')),
                ('h3', models.FloatField(blank=True, null=True, verbose_name='H3 (mm)')),
                ('h4', models.FloatField(blank=True, null=True, verbose_name='H4 (mm)')),
                ('h5', models.FloatField(blank=True, null=True, verbose_name='H5 (mm)')),
                ('h6', models.FloatField(blank=True, null=True, verbose_name='H6 (mm)')),
                ('h7', models.FloatField(blank=True, null=True, verbose_name='H7 (mm)')),
                ('h8', models.FloatField(blank=True, null=True, verbose_name='H8 (mm)')),
                ('d1', models.FloatField(blank=True, null=True, verbose_name='D1 (mm)')),
                ('d2', models.FloatField(blank=True, null=True, verbose_name='D2 (mm)')),
                ('origen', models.CharField(choices=[('terreno', 'Registro en Terreno'), ('excel', 'Importación Excel'), ('api', 'API Externa')], default='terreno', max_length=20)),
                ('horometro', models.FloatField(blank=True, help_text='Horómetro al medir', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_neumaticos', to='equipos.equipo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medición',
                'verbose_name_plural': 'Mediciones',
                'ordering': ['equipo', 'tipo', 'fecha'],
                'indexes': [models.Index(fields=['equipo', 'tipo', 'fecha'], name='neumaticos__equipo__8878d8_idx'), models.Index(fields=['fecha'], name='neumaticos__fecha_2e3a73_idx'), models.Index(fields=['marca_nombre'], name='neumaticos__marca_n_1b09f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Neumatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('traccion', 'Traccional'), ('direccion', 'Direccional')], max_length=20)),
                ('posicion', models.CharField(help_text='Posición: H1-H8 para traccionales, D1-D2 para direccionales', max_length=10)),
                ('serie', models.CharField(blank=True, help_text='Número de serie', max_length=50)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('horometro_instalacion', models.FloatField(default=0, help_text='Horómetro al momento de instalar')),
                ('profundidad_inicial_mm', models.FloatField(blank=True, help_text='Profundidad al instalar (mm). Si vacío, usa valor de fábrica.', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('motivo_retiro', models.CharField(blank=True, max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neumaticos', to='equipos.equipo')),
                ('marca', models.ForeignKey(limit_choices_to={'tipo': 'neumatico'}, on_delete=django.db.models.deletion.PROTECT, related_name='neumaticos', to='equipos.marcacomponente')),
            ],
            options={
                'verbose_name': 'Neumático',
                'verbose_name_plural': 'Neumáticos',
                'ordering': ['equipo', 'tipo', 'posicion'],
                'unique_together': {('equipo', 'tipo', 'posicion', 'activo')},
            },
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('traccion', 'Traccional'), ('direccion', 'Direccional')], max_length=20)),
                ('marca_nombre', models.CharField(max_length=50)),
                ('posicion_critica', models.CharField(help_text='Posición que llega primero al límite', max_length=5)),
                ('valor_actual_mm', models.FloatField()),
                ('horas_restantes', models.FloatField()),
                ('fecha_cambio_estimada', models.DateField()),
                ('fecha_ultima_medicion', models.DateField()),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones_neumaticos', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Proyección',
                'verbose_name_plural': 'Proyecciones',
                'ordering': ['horas_restantes'],
                'unique_together': {('equipo', 'tipo')},
            },
        ),
    ]
