# Generated by Django 5.0.14 on 2026-03-05 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MarcaComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('neumatico', 'Neumático'), ('turbo', 'Turbo'), ('freno', 'Freno'), ('cadena', 'Cadena'), ('otro', 'Otro')], max_length=20)),
                ('profundidad_fabrica_mm', models.FloatField(blank=True, help_text='Profundidad de fábrica en mm (para neumáticos)', null=True)),
                ('vida_util_horas', models.FloatField(blank=True, help_text='Vida útil estimada en horas (referencia)', null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca de Componente',
                'verbose_name_plural': 'Marcas de Componentes',
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('nombre', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número identificador del equipo', unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='operativo', max_length=20)),
                ('horometro_actual', models.FloatField(default=0, help_text='Horómetro actual en horas')),
                ('horas_operacion_diaria', models.FloatField(default=12.5, help_text='Horas promedio de operación diaria')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='equipos.tipoequipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['numero'],
            },
        ),
    ]
