# Generated by Django 5.0.14 on 2026-06-01 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteFreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('del_izq', 'Delantero Izquierdo'), ('del_der', 'Delantero Derecho'), ('tras_izq', 'Trasero Izquierdo'), ('tras_der', 'Trasero Derecho'), ('tras_izq_int', 'Trasero Izq. Interior'), ('tras_der_int', 'Trasero Der. Interior'), ('chasis_izq', 'Chasis Izquierdo'), ('chasis_der', 'Chasis Derecho'), ('medio_izq', 'Medio Izquierdo'), ('medio_der', 'Medio Derecho')], max_length=20)),
                ('tipo_freno', models.CharField(choices=[('disco', 'Disco'), ('tambor', 'Tambor'), ('tambor_aire', 'Tambor de Aire')], default='tambor', max_length=20)),
                ('espesor_fabrica_mm', models.FloatField(help_text='Espesor de la pastilla/balata al instalar (mm). Ref. Kalmar T2: ~20mm. Límite cambio: 6.35mm (0.25")')),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('horometro_instalacion', models.FloatField(blank=True, help_text='Horómetro del equipo al instalar el componente', null=True)),
                ('activo', models.BooleanField(default=True, help_text='True = en servicio. False = reemplazado (histórico)')),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('motivo_retiro', models.CharField(blank=True, choices=[('desgaste', 'Desgaste — Límite alcanzado'), ('daño', 'Daño físico / Fractura'), ('preventivo', 'Mantenimiento Preventivo'), ('otro', 'Otro (ver notas)')], help_text='Razón por la que se retiró este freno', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frenos', to='equipos.equipo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes_freno_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Componente de Freno',
                'verbose_name_plural': 'Componentes de Frenos',
                'ordering': ['equipo', 'posicion', '-activo'],
            },
        ),
        migrations.CreateModel(
            name='MedicionFreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la medición')),
                ('horometro', models.FloatField(blank=True, help_text='Horómetro del equipo al momento de medir', null=True)),
                ('espesor_mm', models.FloatField(help_text='Espesor medido en el punto más delgado (mm). Para discos: espesor de la pastilla. Para tambores: espesor de la balata.')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='frenos.componentefreno')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_freno', to='equipos.equipo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones_freno_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medición de Freno',
                'verbose_name_plural': 'Mediciones de Frenos',
                'ordering': ['componente', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProyeccionFreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espesor_actual_mm', models.FloatField(blank=True, help_text='Espesor medido en la última inspección (mm)', null=True)),
                ('desgaste_pct', models.FloatField(blank=True, help_text='Porcentaje de vida útil consumida (0% = nuevo, 100% = límite alcanzado)', null=True)),
                ('tasa_desgaste_mm_1000h', models.FloatField(default=0.0, help_text='mm desgastados por cada 1000 horas de operación')),
                ('horas_restantes', models.FloatField(default=99999, help_text='Horas estimadas hasta alcanzar el límite de cambio')),
                ('fecha_cambio_estimada', models.DateField(blank=True, help_text='Fecha estimada de cambio según tasa de desgaste', null=True)),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('ATENCION', 'Atención'), ('CRITICO', 'Crítico')], default='OK', max_length=20)),
                ('ultima_medicion_fecha', models.DateField(blank=True, null=True)),
                ('ultima_medicion_horometro', models.FloatField(blank=True, null=True)),
                ('n_mediciones', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('componente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proyeccion', to='frenos.componentefreno')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones_freno', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Proyección de Freno',
                'verbose_name_plural': 'Proyecciones de Frenos',
                'ordering': ['estado', 'horas_restantes'],
            },
        ),
        migrations.AddIndex(
            model_name='componentefreno',
            index=models.Index(fields=['equipo', 'activo'], name='frenos_comp_equipo__d7bee6_idx'),
        ),
        migrations.AddIndex(
            model_name='componentefreno',
            index=models.Index(fields=['equipo', 'posicion', 'activo'], name='frenos_comp_equipo__18d221_idx'),
        ),
        migrations.AddIndex(
            model_name='medicionfreno',
            index=models.Index(fields=['componente', 'fecha'], name='frenos_medi_compone_cf459b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicionfreno',
            index=models.Index(fields=['equipo', 'fecha'], name='frenos_medi_equipo__2a7531_idx'),
        ),
    ]
