# Generated by Django 5.0.14 on 2026-08-17 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0004_add_cha_remove_sts_rtg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opacimetro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(help_text='Ej: TEXA SPA', max_length=60)),
                ('modelo', models.CharField(help_text='Ej: OPABOX Autopower', max_length=60)),
                ('numero_serie', models.CharField(max_length=40, unique=True)),
                ('numero_homologacion', models.CharField(blank=True, max_length=80)),
                ('vencimiento_control', models.DateField(help_text='Vencimiento del control periodico de la camara de analisis')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Opacimetro',
                'verbose_name_plural': 'Opacimetros',
                'ordering': ['fabricante', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='MedicionOpacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, db_index=True, help_text='Semestre de la campana. Ej: 2026-S1. Se calcula solo al guardar.', max_length=7)),
                ('horometro_motor', models.PositiveIntegerField(blank=True, help_text='Horometro del equipo al momento del test (permite normalizar la tendencia)', null=True)),
                ('k_medio', models.FloatField(help_text='Coeficiente de absorcion medio en 1/m')),
                ('k_limite', models.FloatField(default=3.0, help_text='Limite normativo declarado en el informe (1/m). NO se asume, se lee del PDF.')),
                ('aprobado', models.BooleanField(default=True)),
                ('temp_aceite', models.PositiveSmallIntegerField(blank=True, help_text='Grados C', null=True)),
                ('rpm_ralenti', models.PositiveIntegerField(blank=True, null=True)),
                ('rpm_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('calibracion_vigente', models.BooleanField(default=True, help_text='Se evalua contra la FECHA DEL TEST, no contra hoy. Queda congelado.')),
                ('origen', models.CharField(choices=[('PDF', 'Informe PDF'), ('MANUAL', 'Medicion en terreno'), ('HISTORICO', 'Carga historica')], default='PDF', max_length=10)),
                ('campos_manuales', models.JSONField(blank=True, default=list, help_text='Campos marcados con # en el informe (digitados, no medidos por el instrumento)')),
                ('advertencias', models.JSONField(blank=True, default=list)),
                ('operador', models.CharField(blank=True, max_length=80)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='opacidad/%Y/%m/')),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('texto_crudo', models.TextField(blank=True, help_text='Texto extraido del PDF, para auditoria')),
                ('anulado', models.BooleanField(default=False)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opacidades_anuladas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_opacidad', to='equipos.equipo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opacidades_registradas', to=settings.AUTH_USER_MODEL)),
                ('opacimetro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='opacidad.opacimetro')),
            ],
            options={
                'verbose_name': 'Medicion de Opacidad',
                'verbose_name_plural': 'Mediciones de Opacidad',
                'ordering': ['-fecha', 'equipo'],
            },
        ),
        migrations.CreateModel(
            name='ImportacionOpacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='opacidad/importaciones/%Y/%m/')),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('datos_extraidos', models.JSONField(default=dict)),
                ('advertencias', models.JSONField(default=list)),
                ('matricula_detectada', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revision'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=12)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_opacidad', to='equipos.equipo')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_opacidad', to=settings.AUTH_USER_MODEL)),
                ('medicion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacion', to='opacidad.medicionopacidad')),
            ],
            options={
                'verbose_name': 'Importacion de Opacidad',
                'verbose_name_plural': 'Importaciones de Opacidad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProyeccionOpacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_actual', models.FloatField(blank=True, null=True)),
                ('k_limite', models.FloatField(blank=True, null=True)),
                ('pct_limite', models.FloatField(blank=True, help_text='k_actual / k_limite', null=True)),
                ('delta_ultimo', models.FloatField(blank=True, help_text='Variacion respecto del control anterior', null=True)),
                ('tasa_k_anual', models.FloatField(blank=True, help_text='Pendiente de la regresion, en 1/m por ano', null=True)),
                ('tasa_k_1000h', models.FloatField(blank=True, help_text='Pendiente normalizada por horometro, en 1/m cada 1000 h', null=True)),
                ('k_proyectado', models.FloatField(blank=True, help_text='k estimado para el proximo control semestral', null=True)),
                ('semestres_a_limite', models.FloatField(blank=True, null=True)),
                ('n_mediciones', models.PositiveSmallIntegerField(default=0)),
                ('estado', models.CharField(choices=[('OK', 'Ok'), ('ATENCION', 'Atencion'), ('CRITICO', 'Critico')], default='OK', max_length=20)),
                ('motivo_estado', models.CharField(blank=True, max_length=200)),
                ('ultima_medicion_fecha', models.DateField(blank=True, null=True)),
                ('proximo_control', models.DateField(blank=True, null=True)),
                ('control_vencido', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proyeccion_opacidad', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Proyeccion de Opacidad',
                'verbose_name_plural': 'Proyecciones de Opacidad',
                'ordering': ['estado', '-pct_limite'],
            },
        ),
        migrations.CreateModel(
            name='AceleracionOpacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('k', models.FloatField()),
                ('rpm_ralenti', models.PositiveIntegerField(blank=True, null=True)),
                ('rpm_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('tiempo_s', models.FloatField(blank=True, null=True)),
                ('medicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceleraciones', to='opacidad.medicionopacidad')),
            ],
            options={
                'verbose_name': 'Aceleracion',
                'verbose_name_plural': 'Aceleraciones',
                'ordering': ['medicion', 'numero'],
                'unique_together': {('medicion', 'numero')},
            },
        ),
        migrations.AddIndex(
            model_name='medicionopacidad',
            index=models.Index(fields=['equipo', 'fecha'], name='opacidad_me_equipo__0bfbe5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicionopacidad',
            unique_together={('equipo', 'fecha')},
        ),
    ]
