# Generated by Django 5.0.14 on 2026-08-18 16:49

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opacidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacionopacidad',
            name='advertencias',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='importacionopacidad',
            name='datos_extraidos',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='medicionopacidad',
            name='advertencias',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='medicionopacidad',
            name='campos_manuales',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Campos marcados con # en el informe (digitados, no medidos por el instrumento)'),
        ),
    ]
