# Generated by Django 5.0.14 on 2026-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_cambio_neumatico_mm', models.FloatField(default=10.0, help_text='Límite mínimo en mm para alerta de cambio de neumático')),
                ('filtro_pinchazo_neumatico_mm', models.FloatField(default=-10.0, help_text='Cualquier pérdida brusca mayor a este valor (negativo) se asume pinchazo y se filtra del desgaste normal')),
                ('horas_diarias_operacion', models.FloatField(default=12.5, help_text='Promedio de horas diarias de operación por equipo')),
                ('prof_fabrica_neumatico', models.FloatField(default=40.0, help_text='Profundidad de remanente en mm de un neumático nuevo')),
                ('limite_turbo_radial', models.FloatField(default=0.45, help_text='Límite máximo de juego radial permitido en mm')),
                ('limite_turbo_axial', models.FloatField(default=0.15, help_text='Límite máximo de juego axial permitido en mm')),
                ('umbral_alerta_turbo_pct', models.FloatField(default=0.8, help_text='Porcentaje de desgaste (0.0 a 1.0) desde el cual desencadenar alerta de ATENCIÓN')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
