# Generated by Django 5.0.14 on 2026-06-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracionsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='limite_elongacion_cadena_pct',
            field=models.FloatField(default=3.0, help_text='Elongación máxima permitida en % antes de reemplazar la cadena (ISO/industria: 3.0%)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='limite_freno_pastilla_mm',
            field=models.FloatField(default=6.35, help_text='Espesor mínimo de pastilla/balata en mm antes de cambio (Kalmar T2 manual: 6.35 mm / 0.25 inch)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='prof_fabrica_freno_mm',
            field=models.FloatField(default=20.0, help_text='Espesor de fábrica de la pastilla/balata en mm (referencia para cálculo de desgaste %)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='umbral_alerta_cadena_pct',
            field=models.FloatField(default=1.5, help_text='Elongación (%) desde la cual generar alerta ATENCIÓN en cadenas (recomendación industria: 1.5%)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='umbral_alerta_freno_pct',
            field=models.FloatField(default=0.75, help_text='Porcentaje de desgaste (0.0 a 1.0) desde el cual generar alerta ATENCIÓN en frenos'),
        ),
    ]
