# Generated by Django 5.0.14 on 2026-06-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracionsistema_frenos_por_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='limite_freno_pastilla_mm',
            field=models.FloatField(default=6.35, help_text='[Legacy] Límite unificado anterior. Usar limite_freno_tambor_mm / limite_freno_disco_mm según tipo'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='prof_fabrica_freno_mm',
            field=models.FloatField(default=20.0, help_text='[Legacy] Espesor fábrica unificado anterior. Usar prof_fabrica_freno_tambor_mm / _disco_mm'),
        ),
    ]
