# Generated by Django 5.0.14 on 2026-08-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_configuracionsistema_limite_freno_pastilla_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='limite_opacidad_k_default',
            field=models.FloatField(default=3.0, help_text='Coeficiente de absorción máximo en 1/m cuando el informe no lo declara'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='meses_periodicidad_opacidad',
            field=models.IntegerField(default=6, help_text='Periodicidad del control de opacidad en meses (semestral)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='umbral_alerta_opacidad_pct',
            field=models.FloatField(default=0.7, help_text='Fracción del límite (0.0 a 1.0) desde la cual generar alerta ATENCIÓN'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='umbral_critico_opacidad_pct',
            field=models.FloatField(default=0.85, help_text='Fracción del límite (0.0 a 1.0) desde la cual generar alerta CRÍTICO'),
        ),
    ]
