# Generated by Django 5.0.14 on 2026-08-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracionsistema_limite_opacidad_k_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='limite_opacidad_k_porta',
            field=models.FloatField(default=3.0, help_text='Coeficiente de absorción máximo k (1/m) para Portacontenedores / Reach Stackers (GPCO)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='limite_opacidad_k_tracto',
            field=models.FloatField(default=3.0, help_text='Coeficiente de absorción máximo k (1/m) para Terminal Tractos (TETR)'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='limite_opacidad_k_default',
            field=models.FloatField(default=3.0, help_text='Coeficiente de absorción máximo k (1/m) por defecto para otros equipos o chasis'),
        ),
    ]
